t3t:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  feignClient:
    url: ${FEIGN_CLIENT_URL:localhost}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

object-storage:
  storage-url: ${OBJECT_STORAGE_URL}
  auth-url: ${OBJECT_STORAGE_AUTH_URL}
  tenant-id: ${OBJECT_STORAGE_TENANT_ID}
  username: ${OBJECT_STORAGE_USERNAME}
  password: ${OBJECT_STORAGE_PASSWORD}

redis:
  server-ip-address: ${REDIS_SERVER_IP:localhost}
  server-port: ${REDIS_SERVER_PORT:6379}
  server-password: ${REDIS_SERVER_PASSWORD:}
  database: ${REDIS_DATABASE:0}
